services:
  seekarr:
    build:
      context: https://github.com/drew43713/seekarr.git#main
      dockerfile: Dockerfile
    container_name: seekarr
    restart: unless-stopped
    volumes:
      - ./config.json:/config/config.json:ro
      - ./logs:/logs
    environment:
      - SEEKARR_CONFIG=/config/config.json
      - SEEKARR_RUN_AS_CRON=true
      - SEEKARR_CRON_SCHEDULE=0 */12 * * *
      - SEEKARR_DRY_RUN=false
      - SEEKARR_STARTUP_STRICT=true
      # - SEEKARR_SONARR_BASE_URL=http://sonarr:8989/api/v3
      # - SEEKARR_RADARR_BASE_URL=http://radarr:7878/api/v3
      # - SEEKARR_SONARR_API_KEY=your_key_here
      # - SEEKARR_RADARR_API_KEY=your_key_here
